import Head from "next/head"
import "../styles/Home.module.css"
import ListaProdutos from "../service"


export default function Home() {
  return (
    <>
      <Head>
        <title>RESTAURANT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListaProdutos />
    </>
  );
}